name: Web Extension CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "public/**"
      - ".github/**"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "**.md"
      - "public/**"
      - ".github/**"
    branches:
      - master
  workflow_dispatch:

jobs:
  lintBuildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        firefox: ["latest-beta", "latest", "48.0"]
        chrome: ["stable", "beta"]
        browser: ["chromium", "firefox"]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Node set-up
        run: |
          npm ci
          npm install --save-dev web-ext

      - name: Firefox ${{ matrix.firefox }} setup
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Chrome ${{ matrix.chrome }} setup
        if: matrix.browser == 'chromium'
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: ${{ matrix.chrome }}

      - name: ESLint check
        run: npx eslint .

      - name: Extension build
        run: npm run build --if-present

      - name: Web-Ext check on ${{ matrix.browser }}
        run: npx web-ext run
        env:
          WEB_EXT_TARGET: ${{ matrix.browser }}
          WEB_EXT_START_URL: https://quizlet.com/explanations/textbook-solutions/fundamentals-of-physics-10th-edition-9781118230718/chapter-8-problems-3-09b7bd0f-4259-426e-b8d8-cd736420db42
          WEB_EXT_PRE_INSTALL: true
        working-directory: ./dist/build

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version }} == "16.x" && ${{ matrix.browser }} == "firefox" && ${{ matrix.firefox }} == "latest"
        with:
          name: extension
          path: ./dist/build
          if-no-files-found: error
